image: node:latest

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/

stages:
  - verify
  - test
  - publish

codestyle:
  stage: verify
  script:
    - npm ci
    - npm run lint
    # - npm audit
    - npm run build

node:8:
  stage: test
  image: node:8
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm i
    - npm run unit
  coverage: /^All files[^|]*\|[^|]*\s+([\d\.]+)/

node:10:
  stage: test
  image: node:10
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm i
    - npm run unit
  coverage: /^All files[^|]*\|[^|]*\s+([\d\.]+)/

node:latest:
  stage: test
  image: node:latest
  script:
    - npm i
    - npm run unit
  coverage: /^All files[^|]*\|[^|]*\s+([\d\.]+)/

npm:
  stage: publish
  script:
    - VERSION_TAG=$([[ $CI_COMMIT_TAG == *"-rc"* ]] && echo "next" || echo "latest")
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm ci
    - npm run build
    - npm publish --tag $VERSION_TAG
  environment:
    name: npm
    url: https://www.npmjs.com/package/${CI_PROJECT_NAME}
  when: manual
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
