on:
  workflow_run:
    workflows:
      - build
    types:
      - completed
    branches:
      - next

name: Create Beta Release

jobs:
  release:
    name: Release beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
          ref: refs/heads/next
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: git fetch --prune --unshallow
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Get latest changelog
        id: Changelog
        run: |
          changelog=$(npm run --silent get-changelog | tail -n +1)
          echo $changelog
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
      - name: Get release version
        id: release_type
        run: |
          RELEASE_VERSION=`cat VERSION`
          echo "::set-output name=version::$RELEASE_VERSION"
      - name: Create github release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_type.outputs.version }}
          release_name: Release ${{ steps.release_type.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: true

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/next
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Publish
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
